import 'package:flutter/material.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedPetShopWidget1.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedRectangle9Widget1.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedWhoareyouWidget1.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedRectangle10Widget3.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedPetShopWidget2.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedLogo1Widget.dart';
import 'package:flutterfirebaseauth/generatedlandingpage/GeneratedPetMasterWidget1.dart';

/* Frame Registration Page
    Autogenerated by FlutLab FTF Generator
  */
class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 141, 202, 210),
                ),
              ),
              Positioned(
                left: 57.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 49.0,
                child: GeneratedPetShopWidget1(),
              ),
              Positioned(
                left: 100.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 25.0,
                child: GeneratedWhoareyouWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 45.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 142.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedPetMasterWidget1(),
              ),
              Positioned(
                left: 55.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 45.0,
                child: GeneratedRectangle10Widget3(),
              ),
              Positioned(
                left: 148.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 21.0,
                child: GeneratedPetShopWidget2(),
              ),
              Positioned(
                left: 94.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 166.0,
                child: GeneratedLogo1Widget(),
              )
            ]),
      ),
    ));
  }
}
