import 'package:flutter/material.dart';

/* Rectangle logo 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogo1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 170.0,
      height: 166.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/icons/logo.png",
          color: null,
          fit: BoxFit.cover,
          width: 170.0,
          height: 166.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
