import 'package:flutter/material.dart';

/* Text Pet Shop
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPetShopWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Pet Shop''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 18.0,
        fontFamily: 'Ropa Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
