import 'package:flutter/material.dart';

/* Text Pet Shop
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPetShopWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Pet Shop''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 64.0,
        fontFamily: 'Rationale',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
